[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "pkboost"
version = "0.1.0"
description = "Gradient boosting that adapts to concept drift in imbalanced data"
authors = [{name = "Pushp Kharat", email = "kharatpushp16@outlook.com"}]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dependencies = [
    "numpy>=1.20.0",
]

[project.urls]
Homepage = "https://github.com/Pushp-Kharat1/pkboost"
Repository = "https://github.com/Pushp-Kharat1/pkboost"

[tool.maturin]
features = ["pyo3/extension-module"]
